"use client";

import { useState, useRef } from "react";
import { useParams } from "next/navigation";

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} o`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} Ko`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} Mo`;
}

export default function UploadVideoPage() {
  const { token } = useParams<{ token: string }>();
  const [file, setFile] = useState<File | null>(null);
  const [note, setNote] = useState("");
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [progress, setProgress] = useState(0);
  const fileRef = useRef<HTMLInputElement>(null);

  // Token contains encoded info: athleteId:professionnelId:token
  // But actually we pass these via the URL query params generated by the coach
  const searchParams = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : null;
  const athleteId = searchParams?.get("a") || "";
  const professionnelId = searchParams?.get("p") || "";

  const handleUpload = async () => {
    if (!file || !token) return;
    setUploading(true);
    setError("");
    setProgress(0);

    const fd = new FormData();
    fd.append("file", file);
    fd.append("token", token);
    fd.append("athleteId", athleteId);
    fd.append("professionnelId", professionnelId);
    if (note) fd.append("note", note);

    try {
      const res = await fetch("/api/athlete-videos/upload", { method: "POST", body: fd });
      if (!res.ok) {
        const err = await res.json();
        setError(err.error || "Erreur");
        return;
      }
      setSuccess(true);
    } catch {
      setError("Erreur réseau");
    } finally {
      setUploading(false);
    }
  };

  if (success) {
    return (
      <div style={pageStyle}>
        <div style={cardStyle}>
          <div style={{ textAlign: "center" }}>
            <div style={{ fontSize: 48, marginBottom: 16 }}>✅</div>
            <h1 style={{ color: "#fff", fontSize: 22, fontWeight: 800, margin: "0 0 8px" }}>Vidéo envoyée !</h1>
            <p style={{ color: "rgba(255,255,255,0.5)", fontSize: 14 }}>Votre coach recevra la vidéo dans son tableau de bord.</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div style={pageStyle}>
      <div style={cardStyle}>
        <div style={{ textAlign: "center", marginBottom: 28 }}>
          <div style={{ display: "inline-block", background: "linear-gradient(135deg,#f47b20,#ff9a44)", color: "#fff", fontWeight: 800, fontSize: 20, padding: "10px 28px", borderRadius: 12, letterSpacing: -0.5 }}>Tuatha</div>
        </div>

        <h1 style={{ color: "#fff", fontSize: 20, fontWeight: 800, margin: "0 0 4px", textAlign: "center" }}>Envoyer une vidéo</h1>
        <p style={{ color: "rgba(255,255,255,0.4)", fontSize: 13, textAlign: "center", margin: "0 0 28px" }}>Sélectionnez une vidéo à envoyer à votre coach</p>

        {/* File drop */}
        <div
          style={{
            ...dropStyle,
            borderColor: file ? "rgba(244,123,32,0.3)" : "rgba(255,255,255,0.08)",
            background: file ? "rgba(244,123,32,0.03)" : "transparent",
          }}
          onClick={() => fileRef.current?.click()}
        >
          {file ? (
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <span style={{ fontSize: 28 }}>🎬</span>
              <div>
                <div style={{ color: "rgba(255,255,255,0.85)", fontSize: 13, fontWeight: 600 }}>{file.name}</div>
                <div style={{ color: "rgba(255,255,255,0.35)", fontSize: 11 }}>{formatSize(file.size)}</div>
              </div>
            </div>
          ) : (
            <>
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth="1.5"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>
              <span style={{ color: "rgba(255,255,255,0.4)", fontSize: 13 }}>Cliquer pour choisir une vidéo</span>
              <span style={{ color: "rgba(255,255,255,0.2)", fontSize: 11 }}>MP4, MOV, WebM, AVI — Max 200 Mo</span>
            </>
          )}
          <input
            ref={fileRef}
            type="file"
            accept="video/*"
            hidden
            onChange={e => { if (e.target.files?.[0]) setFile(e.target.files[0]); }}
          />
        </div>

        {/* Note */}
        <div style={{ marginTop: 16 }}>
          <label style={{ display: "flex", flexDirection: "column", gap: 6, fontSize: 12, fontWeight: 500, color: "rgba(255,255,255,0.5)" }}>
            Note (optionnel)
            <textarea
              value={note}
              onChange={e => setNote(e.target.value)}
              rows={2}
              placeholder="Ex: Vidéo de mon squat, j'ai une gêne au genou droit..."
              style={textareaStyle}
            />
          </label>
        </div>

        {error && <div style={{ color: "#ef4444", fontSize: 12, marginTop: 12 }}>{error}</div>}

        <button
          onClick={handleUpload}
          disabled={!file || uploading}
          style={{
            ...btnStyle,
            opacity: !file || uploading ? 0.4 : 1,
            cursor: !file || uploading ? "not-allowed" : "pointer",
          }}
        >
          {uploading ? "Envoi en cours..." : "Envoyer la vidéo"}
        </button>
      </div>
    </div>
  );
}

const pageStyle: React.CSSProperties = {
  minHeight: "100vh",
  background: "#0a0a0a",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  padding: 20,
  fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
};

const cardStyle: React.CSSProperties = {
  width: 440,
  maxWidth: "100%",
  background: "rgba(20,20,20,0.95)",
  border: "1px solid rgba(255,255,255,0.06)",
  borderRadius: 20,
  padding: "36px 32px",
  boxShadow: "0 24px 64px rgba(0,0,0,0.5)",
};

const dropStyle: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  gap: 8,
  padding: 32,
  borderRadius: 14,
  border: "2px dashed rgba(255,255,255,0.08)",
  cursor: "pointer",
  transition: "all 0.15s",
};

const textareaStyle: React.CSSProperties = {
  padding: "9px 12px",
  borderRadius: 8,
  background: "rgba(255,255,255,0.04)",
  border: "1px solid rgba(255,255,255,0.06)",
  color: "#fff",
  fontSize: 13,
  outline: "none",
  resize: "vertical",
  fontFamily: "inherit",
};

const btnStyle: React.CSSProperties = {
  width: "100%",
  marginTop: 20,
  padding: "14px 0",
  borderRadius: 12,
  border: "none",
  background: "linear-gradient(135deg, #f47b20, #ff9a44)",
  color: "#fff",
  fontSize: 15,
  fontWeight: 700,
  transition: "all 0.15s",
};
